import { CourseProvider } from "@/povider/CourseProvider";
import Footer from "./components/shared/Footer/Footer";
import Navbars from "./components/shared/Navbars";
import Navigation from "./components/shared/Navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbars />
        <Navigation />
        <CourseProvider>
          <main>{children}</main>
        </CourseProvider>
        <Footer />
      </body>
    </html>
  );
}
