export const course = [
  {
    id: 1,
    title: "Web Development Masterclass",
    subtitle: "Learn to build modern, responsive websites from scratch",
    thumbnail: "/placeholder.svg?height=80&width=120",
    category: "Development",
    price: 99.99,
    discountPrice: 79.99,
    status: "published",
    students: 1245,
    rating: 4.8,
    lastUpdated: "2023-12-15",
  },
  {
    id: 2,
    title: "UI/UX Design Fundamentals",
    subtitle: "Master the principles of user interface and experience design",
    thumbnail: "/placeholder.svg?height=80&width=120",
    category: "Design",
    price: 89.99,
    discountPrice: null,
    status: "draft",
    students: 0,
    rating: 0,
    lastUpdated: "2024-04-02",
  },
  {
    id: 3,
    title: "JavaScript for Beginners",
    subtitle: "Start your journey into programming with JavaScript",
    thumbnail: "/placeholder.svg?height=80&width=120",
    category: "Development",
    price: 49.99,
    discountPrice: 39.99,
    status: "published",
    students: 876,
    rating: 4.6,
    lastUpdated: "2024-01-20",
  },
  {
    id: 4,
    title: "Advanced React Patterns",
    subtitle: "Take your React skills to the next level",
    thumbnail: "/placeholder.svg?height=80&width=120",
    category: "Development",
    price: 129.99,
    discountPrice: 99.99,
    status: "draft",
    students: 0,
    rating: 0,
    lastUpdated: "2024-03-28",
  },
  {
    id: 5,
    title: "Digital Marketing Essentials",
    subtitle: "Learn effective strategies for online marketing",
    thumbnail: "/placeholder.svg?height=80&width=120",
    category: "Marketing",
    price: 79.99,
    discountPrice: null,
    status: "published",
    students: 543,
    rating: 4.5,
    lastUpdated: "2024-02-10",
  },
];
